services:
  backend:
    build:
      context: ./one-time-secret-backend
    ports:
      - '5000:5000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/secretdb
      - SECRET_TTL_MINUTES=10
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s 
      timeout: 10s
      retries: 3  

  frontend:
    build:
      context: ./one-time-secret-frontend
    ports:
      - '3000:80'
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017' 
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 3  

volumes:
  mongo_data:
